name: parkxpert
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

flutter_icons:
  android: true
  ios: true
  image_path: "assests/icon/px.png"
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  getwidget: ^6.0.0
  fluttertoast: ^8.0.9
  google_fonts: ^6.2.1
  rounded_loading_button_plus: ^3.0.1
  intl_phone_number_input: ^0.7.4
  flutter_overlay_window: ^0.4.5
  page_transition: ^2.2.1
  water_drop_nav_bar: ^2.2.2
  appbar_animated: ^0.0.3
  flutter_launcher_icons: ^0.14.3
  input_validator: ^0.0.3
  font_awesome_flutter: ^10.8.0
  flip_drawer_3d: ^0.0.3
  double_tap_exit: ^0.0.11
  double_tap_to_exit: ^1.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.4
  geolocator: ^13.0.2
  get: ^4.7.2
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  animated_confirm_dialog: ^1.0.2
  permission_handler: ^11.4.0
  flutter_map: ^8.1.0
  awesome_dialog: ^3.2.1
  geocoding: ^3.0.0
  flutter_image_compress: ^2.4.0
  micro_loaders: ^0.0.5
  flutter_rating_bar: ^4.0.1
  http: ^1.4.0
  flutter_stripe: 11.5.0
  shimmer: ^3.0.0
  intl: ^0.20.0
  fl_chart: ^1.0.0
  get_storage: ^2.1.1
  flutter_slidable: ^4.0.0
  splash_view: ^2.0.1
  connectivity_plus: ^6.0.3
  lottie_screen_onboarding_flutter: ^1.1.3
  lottie: ^3.3.1
  syncfusion_flutter_charts: ^30.1.42
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/default_profile_pic.jfif
    - assets/images/Nodata.png
    - assets/images/auth.jpg
    - assets/images/splash.png
    - assets/images/marker.png
    - assets/images/parking.png
    - assets/images/bg1.png
    - assets/animations/approve.json
    - assets/animations/earning.json
    - assets/animations/fastpay.json
    - assets/animations/NearBy.json
    - assets/animations/welcome.json
    - assets/animations/earth.json
    - assets/animations/finding.json
    - assets/animations/Nonearby.json
    - assets/animations/No_data.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
